<?php defined( 'ABSPATH' ) OR die( 'This script cannot be accessed directly.' );

/**
 * Theme's shortcodes
 *
 * @filter wlgx_config_shortcodes
 */
global $wlgx_template_directory;

$social_links = wlgx_config( 'social_links' );

$social_links_config = array();

foreach ( $social_links as $name => $title ) {
	$social_links_config[$name] = '';
}

return array(

	/**
	 * Overloading existing and registering new shortcodes
	 */
	'vc_row' => array(
		'atts' => array(
			'content_placement' => 'default',
			'columns_type' => 'default',
			'gap' => '',
			'height' => 'medium',
			'valign' => '',
			'width' => '',
			'color_scheme' => '',
			'wlgx_bg_color' => '',
			'wlgx_text_color' => '',
			'wlgx_bg_image' => '',
			'wlgx_bg_size' => 'cover',
			'wlgx_bg_repeat' => 'repeat',
			'wlgx_bg_pos' => 'center center',
			'wlgx_bg_parallax' => '',
			'wlgx_bg_parallax_width' => '130',
			'wlgx_bg_parallax_reverse' => FALSE,
			'wlgx_bg_video' => '',
			'wlgx_bg_overlay_color' => '',
			'el_id' => '',
			'el_class' => '',
			'disable_element' => '',
			'css' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_row.php',
	),
	'vc_row_inner' => array(
		'atts' => array(
			'content_placement' => 'default',
			'columns_type' => 'default',
			'gap' => '',
			'el_id' => '',
			'el_class' => '',
			'disable_element' => '',
			'css' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_row_inner.php',
	),
	'vc_column' => array(
		'atts' => array(
			'width' => '1/1',
			'text_color' => '',
			'animate' => '',
			'animate_delay' => 0,
			'el_class' => '',
			'offset' => '',
			'css' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_column.php',
	),
	'vc_column_inner' => array(
		'atts' => array(
			'width' => '1/1',
			'text_color' => '',
			'animate' => '',
			'animate_delay' => 0,
			'el_class' => '',
			'offset' => '',
			'css' => '',
		),
		'alias_of' => 'vc_column',
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_column_inner.php',
	),
	'vc_column_text' => array(
		'atts' => array(
			'el_class' => '',
			'css' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_column_text.php',
	),
	'wlgx_single_image' => array(
		'atts' => array(
			'image' => '',
			'size' => 'large',
			'align' => '',
			'lightbox' => FALSE,
			'link' => '',
			'frame' => 'none',
			'animate' => '',
			'animate_delay' => 0,
			'el_class' => '',
			'css' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_single_image.php',
	),
	'wlgx_gallery' => array(
		'atts' => array(
			'ids' => '',
			'columns' => 6,
			'layout' => 'default',
			'masonry' => FALSE,
			'orderby' => '',
			'indents' => FALSE,
			'meta' => FALSE,
			'meta_style' => 'simple',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_gallery.php',
	),
	'gallery' => array(
		'alias_of' => 'wlgx_gallery',
	),
	'wlgx_image_slider' => array(
		'atts' => array(
			'ids' => '',
			'arrows' => 'always',
			'nav' => 'none',
			'transition' => 'slide',
			'autoplay' => FALSE,
			'autoplay_period' => 3000,
			'fullscreen' => FALSE,
			'meta' => FALSE,
			'orderby' => '',
			'img_size' => 'large',
			'img_fit' => 'scaledown',
			'frame' => 'none',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_image_slider.php',
	),
	'wlgx_separator' => array(
		'atts' => array(
			'type' => 'default',
			'size' => 'medium',
			'thick' => '1',
			'style' => 'solid',
			'color' => 'border',
			'bdcolor' => '',
			'icon' => '',
			'text' => '',
			'title_tag' => 'h6',
			'title_size' => '',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_separator.php',
	),
	'wlgx_btn' => array(
		'atts' => array(
			'text' => __( 'Click Me', 'wlgx' ),
			'link' => '',
			'color' => 'primary',
			'bg_color' => '',
			'text_color' => '',
			'style' => 'solid',
			'icon' => '',
			'iconpos' => 'left',
			'size' => '15px',
			'align' => 'left',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_btn.php',
	),
	'vc_tta_tabs' => array(
		'atts' => array(
			'layout' => 'default',
			'stretch' => FALSE,
			'title_size' => '',
			'el_class' => '',
			'css' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_tta_tabs.php',
	),
	'vc_tabs' => array(
		'alias_of' => 'vc_tta_tabs',
	),
	'vc_tta_accordion' => array(
		'atts' => array(
			'toggle' => FALSE,
			'c_align' => 'left',
			'c_icon' => 'chevron',
			'c_position' => 'right',
			'title_tag' => 'h5',
			'title_size' => '',
			'el_class' => '',
			'css' => '',
		),
		'alias_of' => 'vc_tta_tabs',
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_tta_accordion.php',
	),
	'vc_accordion' => array(
		'alias_of' => 'vc_tta_tabs',
	),
	'vc_tta_tour' => array(
		'atts' => array(
			'c_align' => 'left',
			'tab_position' => 'left',
			'controls_size' => 'auto',
			'title_size' => '',
			'el_class' => '',
			'css' => '',
		),
		'alias_of' => 'vc_tta_tabs',
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_tta_tour.php',
	),
	'vc_tta_section' => array(
		'atts' => array(
			'title' => '',
			'tab_id' => '',
			'icon' => '',
			'i_position' => 'left',
			'active' => FALSE,
			'indents' => '',
			'bg_color' => '',
			'text_color' => '',
			'c_position' => 'right',
			'title_tag' => 'h5',
			'title_size' => '',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_tta_section.php',
	),
	'vc_tab' => array(
		'alias_of' => 'vc_tta_section',
	),
	'vc_accordion_tab' => array(
		'alias_of' => 'vc_tta_section',
	),
	'wlgx_iconbox' => array(
		'atts' => array(
			'icon' => 'fa-star',
			'style' => 'default',
			'color' => 'primary',
			'icon_color' => FALSE,
			'bg_color' => FALSE,
			'iconpos' => 'top',
			'size' => '36px',
			'title' => '',
			'title_tag' => 'h4',
			'title_size' => '',
			'link' => '',
			'img' => '',
			'el_class' => '',
		),
		'content' => '',
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_iconbox.php',
	),
	'wlgx_testimonial' => array(
		'atts' => array(
			'style' => 1,
			'author' => 'John Doe',
			'company' => 'wwwlogix Client',
			'img' => '',
			'link' => '',
			'el_class' => '',
		),
		'content' => 'Text goes here',
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_testimonial.php',
	),
	'wlgx_testimonials' => array(
		'atts' => array(
			'type' => 'grid',
			'arrows' => FALSE,
			'dots' => TRUE,
			'auto_scroll' => FALSE,
			'interval' => 3,
			'columns' => 3,
			'orderby' => 'date',
			'style' => 1,
			'text_size' => '',
			'items' => '',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_testimonials.php',
	),
	'wlgx_person' => array(
		'atts' => array(
			'image' => '',
			'image_hover' => '',
			'name' => 'John Doe',
			'role' => 'wwwlogix Team',
			'layout' => 'circle',
			'effect' => 'none',
			'link' => '',
			'email' => '',
			'facebook' => '',
			'twitter' => '',
			'google_plus' => '',
			'linkedin' => '',
			'skype' => '',
			'custom_icon' => '',
			'custom_link' => '',
			'el_class' => '',
		),
		'content' => '',
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_person.php',
	),
	'wlgx_casestudy' => array(
		'atts' => array(
			'columns' => 3,
			'pagination' => 'none',
			'items' => '',
			'style' => 'style_1',
			'align' => 'center',
			'ratio' => '1x1',
			'meta' => '',
			'with_indents' => FALSE,
			'orderby' => 'date',
			'title_size' => '',
			'meta_size' => '',
			'text_color' => '',
			'bg_color' => '',
			'el_class' => '',
			'categories' => NULL,
			'filter' => 'none',
			'filter_style' => 'style_1',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_casestudy.php',
	),
	'wlgx_blog' => array(
		'atts' => array(
			'layout' => 'classic',
			'columns' => 2,
			'masonry' => FALSE,
			'items' => NULL,
			'pagination' => 'none',
			'show_date' => TRUE,
			'show_author' => TRUE,
			'show_categories' => TRUE,
			'show_tags' => TRUE,
			'show_comments' => TRUE,
			'show_read_more' => TRUE,
			'content_type' => 'excerpt',
			'orderby' => 'date',
			'title_size' => '',
			'meta_size' => '',
			'el_class' => '',
			'categories' => NULL,
			'filter' => 'none',
			'filter_style' => 'style_1',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_blog.php',
	),
	'wlgx_logos' => array(
		'atts' => array(
			'type' => 'carousel',
			'columns' => 5,
			'with_indents' => FALSE,
			'style' => 1,
			'arrows' => FALSE,
			'dots' => FALSE,
			'auto_scroll' => FALSE,
			'interval' => 3,
			'orderby' => '',
			'items' => array(),
			'el_class' => '',
		),
		'items_atts' => array(
			'image' => '',
			'link' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_logos.php',
	),
	'wlgx_cta' => array(
		'atts' => array(
			'title' => 'This is ActionBox',
			'color' => 'primary',
			'bg_color' => '',
			'text_color' => '',
			'title_tag' => 'h2',
			'controls' => 'right',
			'btn_label' => __( 'Click Me', 'wlgx' ),
			'btn_link' => '',
			'btn_color' => 'primary',
			'btn_bg_color' => '',
			'btn_text_color' => '',
			'btn_style' => 'solid',
			'btn_size' => '15px',
			'btn_icon' => '',
			'btn_iconpos' => 'left',
			'second_button' => FALSE,
			'btn2_label' => __( 'Click Me', 'wlgx' ),
			'btn2_link' => '',
			'btn2_color' => 'secondary',
			'btn2_bg_color' => '',
			'btn2_text_color' => '',
			'btn2_style' => 'solid',
			'btn2_size' => '15px',
			'btn2_icon' => '',
			'btn2_iconpos' => 'left',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_cta.php',
	),
	'vc_video' => array(
		'atts' => array(
			'link' => 'https://youtu.be/XuWr9gJa6P0',
			'video_related' => FALSE,
			'video_title' => TRUE,
			'ratio' => '16x9',
			'max_width' => '',
			'align' => 'left',
			'css' => '',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_video.php',
	),
	'wlgx_message' => array(
		'atts' => array(
			'color' => 'info',
			'bg_color' => '',
			'text_color' => '',
			'icon' => '',
			'closing' => FALSE,
			'el_class' => '',
		),
		'content' => 'I am message box. Click edit button to change this text.',
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_message.php',
	),
	'wlgx_counter' => array(
		'atts' => array(
			'initial' => '0',
			'target' => '99',
			'prefix' => '',
			'suffix' => '',
			'color' => 'text',
			'custom_color' => '',
			'size' => 'medium',
			'title' => __( 'Projects completed', 'wlgx' ),
			'title_tag' => 'h6',
			'title_size' => '',
			'align' => 'center',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_counter.php',
	),
	'wlgx_cform' => array(
		'atts' => array(
			'receiver_email' => get_option( 'admin_email' ),
			'name_field' => 'required',
			'email_field' => 'required',
			'phone_field' => 'required',
			'message_field' => 'required',
			'captcha_field' => 'hidden',
			'button_color' => 'primary',
			'button_bg_color' => '',
			'button_text_color' => '',
			'button_style' => 'solid',
			'button_size' => '15px',
			'button_align' => 'left',
			'button_text' => '',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_cform.php',
	),
	'wlgx_sharing' => array(
		'atts' => array(
			'type' => 'simple',
			'align' => 'left',
			'color' => 'default',
			'counters' => 'show',
			'email' => FALSE,
			'facebook' => TRUE,
			'twitter' => TRUE,
			'linkedin' => FALSE,
			'gplus' => TRUE,
			'pinterest' => FALSE,
			'vk' => FALSE,
			'url' => '',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_sharing.php',
	),
	'wlgx_social_links' => array(
		'atts' => array_merge(
			array(
				'email' => '',
			), $social_links_config, array(
				'custom_link' => '',
				'custom_title' => '',
				'custom_icon' => '',
				'custom_color' => '#1abc9c',
				'style' => 'default',
				'color' => 'brand',
				'size' => '20px',
				'align' => 'left',
				'el_class' => '',
			)
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_social_links.php',
	),
	'wlgx_gmaps' => array(
		'atts' => array(
			'marker_address' => '1600 Amphitheatre Parkway, Mountain View, CA 94043, United States',
			'marker_text' => base64_encode( '<h6>Hey, we are here!</h6><p>We will be glad to see you in our office.</p>' ),
			'show_infowindow' => FALSE,
			'markers' => '',
			'custom_marker_img' => '',
			'custom_marker_size' => 20,
			'height' => 400,
			'type' => 'roadmap',
			'zoom' => 14,
			'latitude' => '',
			'longitude' => '',
			'api_key' => '',
			'hide_controls' => FALSE,
			'disable_zoom' => FALSE,
			'disable_dragging' => FALSE,
			'map_bg_color' => '',
			'map_style_json' => '',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_gmaps.php',
	),
	'wlgx_pricing' => array(
		'atts' => array(
			'style' => '1',
			'items' => '',
			'el_class' => '',
		),
		'items_atts' => array(
			'title' => 'New Item',
			'type' => 'default',
			'price' => '$99',
			'substring' => 'per month',
			'features' => '',
			'btn_text' => 'Sign up',
			'btn_color' => 'primary',
			'btn_bg_color' => '',
			'btn_text_color' => '',
			'btn_style' => 'solid',
			'btn_size' => '15px',
			'btn_icon' => '',
			'btn_iconpos' => 'left',
			'btn_link' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_pricing.php',
	),
	'wlgx_contacts' => array(
		'atts' => array(
			'address' => '',
			'phone' => '',
			'fax' => '',
			'email' => '',
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_contacts.php',
	),
	'wlgx_progbar' => array(
		'atts' => array(
			'title' => 'This is Progress Bar',
			'count' => '50',
			'style' => '1',
			'color' => 'primary',
			'bar_color' => '',
			'size' => 'medium',
			'hide_count' => FALSE,
			'el_class' => '',
		),
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/wlgx_progbar.php',
	),
	'vc_custom_heading' => array(
		'overload' => FALSE,
		'custom_vc_map' => $wlgx_template_directory . '/framework/plugins-support/js_composer/map/vc_custom_heading.php',
	),
	/**
	 * Backward compatibility
	 */
	'vc_separator' => array(
		'alias_of' => 'wlgx_separator',
	),
	'vc_text_separator' => array(
		'alias_of' => 'wlgx_separator',
	),
	'vc_message' => array(
		'alias_of' => 'wlgx_message',
	),
	'vc_single_image' => array(
		'alias_of' => 'wlgx_single_image',
	),
	'vc_gallery' => array(
		'alias_of' => 'wlgx_gallery',
	),
	'vc_gmaps' => array(
		'alias_of' => 'wlgx_gmaps',
	),
	/**
	 * Shortcodes that are not supported by the theme, and should be temporarily disabled
	 */
	'vc_icon' => array(
		'supported' => FALSE,
	),
	'vc_btn' => array(
		'supported' => FALSE,
	),
	'vc_facebook' => array(
		'supported' => FALSE,
	),
	'vc_tweetmeme' => array(
		'supported' => FALSE,
	),
	'vc_googleplus' => array(
		'supported' => FALSE,
	),
	'vc_pinterest' => array(
		'supported' => FALSE,
	),
	'vc_flickr' => array(
		'supported' => FALSE,
	),
	'vc_tta_pageable' => array(
		'supported' => FALSE,
	),
	'vc_toggle' => array(
		'supported' => FALSE,
	),
	'vc_tour' => array(
		'supported' => FALSE,
	),
	'vc_posts_slider' => array(
		'supported' => FALSE,
	),
	'vc_progress_bar' => array(
		'supported' => FALSE,
	),
	'vc_pie' => array(
		'supported' => FALSE,
	),
	'vc_basic_grid' => array(
		'supported' => FALSE,
	),
	'vc_media_grid' => array(
		'supported' => FALSE,
	),
	'vc_images_carousel' => array(
		'supported' => FALSE,
	),
	'vc_masonry_grid' => array(
		'supported' => FALSE,
	),
	'vc_masonry_media_grid' => array(
		'supported' => FALSE,
	),
	'vc_section' => array(
		'supported' => FALSE,
	),

);
